{
  "openapi": "3.0.1",
  "info": {
    "title": "FICOBA_API",
    "description" : "Offres de services REST de l'API FICOBA - Restitution \n\nPour plus d'informations sur cette API et ses différents webservices, vous pouvez vous référer à son [protocole technique](/resources/ProtocoleTechniqueFicoba3-v5.pdf).",
    "version": "v2"
  },
  "servers": [{ "url": "https://10.156.14.219:468/ficoba-api/v2" }],
  "paths": {
    "/etatSante": {
      "get": {
        "tags": ["Etat Santé"],
        "description": "Vérifier le statut de l'API",
        "operationId": "getInfo",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "responses": {
          "200": {
            "description": "L'API est disponible",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/EtatSante" }
              }
            }
          },
          "503": {
            "description": "L'API est actuellement indisponible",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResultatErreurApiSante"
                }
              }
            }
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/numCpte": {
      "post": {
        "tags": ["OS041 - RechercherComptesParNumCpte"],
        "description": "Rechercher compte clos et actif par numero compte",
        "operationId": "rechercherCompteParNumCpte",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DemandeRestitRechCompte"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseListeFinaleComptes"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/siretSiren": {
      "post": {
        "tags": ["OS044 - RechercherComptesParSiretSiren"],
        "description": "Rechercher compte par SIRET SIREN",
        "operationId": "rechercherCompteParSiretSiren",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DemandeRestitSiretSiren"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseListeFinaleComptesPourPM"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/spi": {
      "post": {
        "tags": ["OS045 - RechercherComptesParSpi"],
        "description": "Rechercher compte par Spi",
        "operationId": "rechercherComptesSpi",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/DemandeRestitRechSpi" }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche  effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseListeFinaleComptesPourPP"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/perPhy": {
      "post": {
        "tags": ["OS043 - RechercherComptesPerPhy"],
        "description": "Rechercher les comptes pour une personne physique",
        "operationId": "rechercherComptesPersonnePhysique",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DemandeRestitRechPerPhy"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche comptes personne physique effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseListeFinaleComptesPourPP"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/perPro": {
      "post": {
        "tags": ["OS042 - RechercherComptesPerPro"],
        "description": "Rechercher les comptes d'une personne morale",
        "operationId": "rechercherComptesPerPro",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DemandeRestitRechPerPro"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseListeFinaleComptesPourPM"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/multiDet": {
      "post": {
        "tags": ["OS035 - RechercherMutiDetention"],
        "description": "Rechercher compte réglementé",
        "operationId": "rechercherMultiDetention",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/DemandeRestitMultiDet" }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche  effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseMultiDetention"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    },
    "/comptes/verifIban": {
      "post": {
        "tags": ["OS050 - VerifierTitulaireIban"],
        "description": "Verifier le titulaire d'un iban",
        "operationId": "rechercherCompteParNumCpte_1",
        "parameters": [
          { "$ref": "#/components/parameters/paramAuthorization" },
          { "$ref": "#/components/parameters/XCorrelationID" }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DemandeRestitVerifIban"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Recherche effectuée avec succés ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReponseListeFinaleComptes"
                }
              }
            }
          },
          "400": {
            "description": "Erreur pendant le traitement de la recherche"
          },
          "default": { "$ref": "#/components/responses/defaultErrorApim" }
        },
        "security": [{ "default": [] }],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "7000_appels_par_min"
      }
    }
  },
  "components": {
    "schemas": {
      "EtatSante": {
        "type": "object",
        "properties": {
          "descriptif": {
            "type": "string",
            "description": "L'API est opérationnelle",
            "example": "L'API est opérationnelle"
          }
        }
      },
      "ReponseErreur": {
        "type": "object",
        "properties": {
          "code": { "type": "string" },
          "message": { "type": "string" },
          "horodatage": { "type": "string" }
        }
      },
      "ResultatErreurApiSante": {
        "type": "object",
        "properties": {
          "erreur": { "$ref": "#/components/schemas/ReponseErreur" }
        }
      },
      "AdresseGuichet": {
        "type": "object",
        "properties": {
          "libAdr1": { "type": "string" },
          "libAdr2": { "type": "string" },
          "libAdr3": { "type": "string" },
          "libAdr4": { "type": "string" }
        }
      },
      "CaracteristiqueCompte": {
        "type": "object",
        "properties": {
          "codeCaracteristique": { "type": "integer", "format": "int32" },
          "libelleCaracteristique": { "type": "string" }
        }
      },
      "CompteCaracteristiques": {
        "type": "object",
        "properties": {
          "iban": { "type": "string" },
          "dateOuverture": { "type": "string" },
          "dateFiscale": { "type": "string" },
          "motifOuverture": { "type": "string" },
          "dateCloture": { "type": "string" },
          "nature": { "$ref": "#/components/schemas/NatureCompteDto" },
          "type": { "$ref": "#/components/schemas/TypeCompte" },
          "formatCompte": { "type": "string" },
          "caracteristique": {
            "$ref": "#/components/schemas/CaracteristiqueCompte"
          },
          "succession": { "type": "string" },
          "resident": { "type": "string" },
          "devise": { "$ref": "#/components/schemas/DeviseCompte" }
        }
      },
      "CompteStructure": {
        "type": "object",
        "properties": {
          "caracteristiqueCompte": {
            "$ref": "#/components/schemas/CompteCaracteristiques"
          },
          "etablissementGestionnaire": {
            "$ref": "#/components/schemas/EtablissementGestionnaire"
          },
          "ayantsDroits": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/TitulaireCompte" }
          }
        }
      },
      "DemandeRestit": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" }
        }
      },
      "DeviseCompte": {
        "type": "object",
        "properties": { "codeDevise": { "type": "string" } }
      },
      "EtablissementBancaire": {
        "type": "object",
        "properties": {
          "numeroEtablissement": { "type": "string" },
          "libelleEtablissement": { "type": "string" },
          "bicEtablissement": { "type": "string" }
        }
      },
      "EtablissementGestionnaire": {
        "type": "object",
        "properties": {
          "etablissement": {
            "$ref": "#/components/schemas/EtablissementBancaire"
          },
          "guichet": { "$ref": "#/components/schemas/GuichetDto" }
        }
      },
      "GuichetDto": {
        "type": "object",
        "properties": {
          "numeroGuichet": { "type": "string" },
          "libelleGuichet": { "type": "string" },
          "adresse": { "$ref": "#/components/schemas/AdresseGuichet" }
        }
      },
      "NatureCompteDto": {
        "type": "object",
        "properties": {
          "codeNature": { "type": "integer", "format": "int32" },
          "libelleNature": { "type": "string" }
        }
      },
      "ReponseListeComptes": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "comptes": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/CompteStructure" }
          },
          "verificationCompte": {
            "$ref": "#/components/schemas/ReponseVerifCompte"
          }
        }
      },
      "ReponseListeFinaleComptes": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "reponses": { "$ref": "#/components/schemas/ReponseListeComptes" }
        }
      },
      "ReponseVerifCompte": {
        "type": "object",
        "properties": {
          "ibanExistant": { "type": "string" },
          "dateCloture": { "type": "string" }
        }
      },
      "TitulaireCompte": { "type": "object" },
      "TypeCompte": {
        "type": "object",
        "properties": {
          "codeType": { "type": "integer", "format": "int32" },
          "libelleType": { "type": "string" }
        }
      },
      "CriteresRechercheCompte": {
        "type": "object",
        "properties": {
          "iban": { "type": "string" },
          "verificationCompte": { "type": "string" }
        }
      },
      "DemandeRestitRechCompte": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRechercheCompte"
          }
        }
      },
      "Adresse": {
        "type": "object",
        "properties": {
          "codePaysResidence": { "type": "string" },
          "libellePaysResidence": { "type": "string" },
          "codeDepartementResidence": { "type": "string" },
          "libelleDepartementResidence": { "type": "string" },
          "codeCommuneResidence": { "type": "string" },
          "libelleCommuneResidence": { "type": "string" },
          "codeNatureVoie": { "type": "string" },
          "libelleVoie": { "type": "string" },
          "numeroVoie": { "type": "string" },
          "indiceRepetition": { "type": "string" },
          "indicateurCodifAdresse": { "type": "string" },
          "codePostal": { "type": "string" },
          "libelleComplAdr": { "type": "string" }
        }
      },
      "PersonneMorale": {
        "type": "object",
        "properties": {
          "raisonSociale": { "type": "string" },
          "sigle": { "type": "string" },
          "enseigne": { "type": "string" },
          "siret": { "type": "string" },
          "categorieJuridique": { "type": "integer", "format": "int32" },
          "siren": { "type": "string" },
          "adresse": { "$ref": "#/components/schemas/Adresse" },
          "scoreAppariement": { "type": "number", "format": "double" }
        }
      },
      "ReponseListeComptesPourPM": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "personneRecherche": {
            "$ref": "#/components/schemas/PersonneMorale"
          },
          "nombreComptes": { "type": "string" },
          "comptes": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/CompteStructure" }
          }
        }
      },
      "ReponseListeFinaleComptesPourPM": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "reponses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ReponseListeComptesPourPM"
            }
          }
        }
      },
      "CriteresRechercheSiretSiren": {
        "type": "object",
        "properties": {
          "siret": { "type": "string" },
          "siren": { "type": "string" }
        }
      },
      "DemandeRestitSiretSiren": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRechercheSiretSiren"
          }
        }
      },
      "CommuneNaissance": {
        "type": "object",
        "properties": {
          "codeCommune": { "type": "string" },
          "libelleCommune": { "type": "string" }
        }
      },
      "DepartementNaissance": {
        "type": "object",
        "properties": {
          "codeDepartement": { "type": "string" },
          "libelleDepartement": { "type": "string" }
        }
      },
      "PaysNaissance": {
        "type": "object",
        "properties": {
          "codePays": { "type": "string" },
          "libellePays": { "type": "string" }
        }
      },
      "PersonnePhysique": {
        "type": "object",
        "properties": {
          "nomNaissance": { "type": "string" },
          "nomUsage": { "type": "string" },
          "prenom": { "type": "string" },
          "sexe": { "type": "string" },
          "anneeNaissance": { "type": "string" },
          "moisNaissance": { "type": "string" },
          "jourNaissance": { "type": "string" },
          "dateDeces": { "type": "string" },
          "paysNaissance": { "$ref": "#/components/schemas/PaysNaissance" },
          "departementNaissance": {
            "$ref": "#/components/schemas/DepartementNaissance"
          },
          "communeNaissance": {
            "$ref": "#/components/schemas/CommuneNaissance"
          },
          "numeroSpi": { "type": "integer", "format": "int64" },
          "adresse": { "$ref": "#/components/schemas/Adresse" },
          "scoreAppariement": { "type": "number", "format": "double" }
        }
      },
      "ReponseListeComptesPourPP": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "personneRecherche": {
            "$ref": "#/components/schemas/PersonnePhysique"
          },
          "nombreComptes": { "type": "string" },
          "comptes": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/CompteStructure" }
          }
        }
      },
      "ReponseListeFinaleComptesPourPP": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "reponses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ReponseListeComptesPourPP"
            }
          }
        }
      },
      "CriteresRechercheSpi": {
        "type": "object",
        "properties": { "numeroSPI": { "type": "string" } }
      },
      "DemandeRestitRechSpi": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRechercheSpi"
          }
        }
      },
      "CriteresRecherchePerPhy": {
        "type": "object",
        "properties": {
          "etatCivil": { "$ref": "#/components/schemas/EtatCivil" },
          "lieuNaissance": { "$ref": "#/components/schemas/LieuNaissance" },
          "domiciliation": { "$ref": "#/components/schemas/Domiciliation" }
        }
      },
      "DemandeRestitRechPerPhy": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRecherchePerPhy"
          }
        }
      },
      "Domiciliation": {
        "type": "object",
        "properties": {
          "codePays": { "type": "string" },
          "codeDepartement": { "type": "string" },
          "codeCommune": { "type": "string" },
          "codeNatureVoie": { "type": "string" },
          "libelleVoie": { "type": "string" },
          "numeroVoie": { "type": "string" },
          "indiceRepetition": { "type": "string" },
          "codePostal": { "type": "string" }
        }
      },
      "EtatCivil": {
        "type": "object",
        "properties": {
          "anneeNaissance": { "type": "string" },
          "moisNaissance": { "type": "string" },
          "jourNaissance": { "type": "string" },
          "anneeNaissanceDebut": { "type": "string" },
          "moisNaissanceDebut": { "type": "string" },
          "jourNaissanceDebut": { "type": "string" },
          "anneeNaissanceFin": { "type": "string" },
          "moisNaissanceFin": { "type": "string" },
          "jourNaissanceFin": { "type": "string" },
          "nom": { "type": "string" },
          "prenoms": { "type": "string" },
          "sexe": { "type": "string" }
        }
      },
      "LieuNaissance": {
        "type": "object",
        "properties": {
          "codePaysNaissance": { "type": "string" },
          "codeDepartementNaissance": { "type": "string" },
          "codeCommuneNaissance": { "type": "string" }
        }
      },
      "CriteresRecherchePerPro": {
        "type": "object",
        "properties": {
          "designation": { "$ref": "#/components/schemas/Designation" },
          "domiciliation": { "$ref": "#/components/schemas/Domiciliation" }
        }
      },
      "DemandeRestitRechPerPro": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRecherchePerPro"
          }
        }
      },
      "Designation": {
        "type": "object",
        "properties": {
          "raisonSociale": { "type": "string" },
          "sigle": { "type": "string" },
          "enseigne": { "type": "string" },
          "codeCategorieJuridique": { "type": "string" }
        }
      },
      "CompteMultiDet": {
        "type": "object",
        "properties": {
          "iban": { "type": "string" },
          "nature": { "type": "string" },
          "dateOuverture": { "type": "string" },
          "dateFiscale": { "type": "string" },
          "motifOuverture": { "type": "string" },
          "codeEtab": { "type": "string" },
          "guichet": { "$ref": "#/components/schemas/GuichetDto" }
        }
      },
      "ReponseMultiDetention": {
        "type": "object",
        "properties": {
          "caracteristiquesDemande": {
            "$ref": "#/components/schemas/DemandeRestit"
          },
          "referenceDemande": { "type": "string" },
          "nombreReponses": { "type": "string" },
          "messageInformatif": { "$ref": "#/components/schemas/ReponseErreur" },
          "getnRep": { "type": "string" },
          "comptes": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/CompteMultiDet" }
          }
        }
      },
      "CriteresRechercheMultiDet": {
        "type": "object",
        "properties": {
          "accordClient": { "type": "string" },
          "codeNatureCompte": { "type": "string" },
          "recherchePP": { "type": "string" },
          "recherchePM": { "type": "string" },
          "rechercheSIRENSIRET": { "type": "string" },
          "criteresRecherchePro": {
            "$ref": "#/components/schemas/CriteresRecherchePerPro"
          },
          "criteresRecherchePhy": {
            "$ref": "#/components/schemas/CriteresRecherchePerPhyMD"
          },
          "criteresSiretSiren": {
            "$ref": "#/components/schemas/CriteresRechercheSiretSiren"
          }
        }
      },
      "CriteresRecherchePerPhyMD": {
        "type": "object",
        "properties": {
          "etatCivil": { "$ref": "#/components/schemas/EtatCivilTitulaire" },
          "lieuNaissance": { "$ref": "#/components/schemas/LieuNaissance" },
          "domiciliation": { "$ref": "#/components/schemas/Domiciliation" }
        }
      },
      "DemandeRestitMultiDet": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRechercheMultiDet"
          }
        }
      },
      "EtatCivilTitulaire": {
        "type": "object",
        "properties": {
          "nom": { "type": "string" },
          "prenoms": { "type": "string" },
          "sexe": { "type": "string" },
          "anneeNaissance": { "type": "string" },
          "moisNaissance": { "type": "string" },
          "jourNaissance": { "type": "string" }
        }
      },
      "CriteresRechercheVerifTitulaireIban": {
        "type": "object",
        "properties": {
          "iban": { "type": "string" },
          "recherchePP": { "type": "string" },
          "recherchePM": { "type": "string" },
          "rechercheSirenSiret": { "type": "string" },
          "etatCivil": { "$ref": "#/components/schemas/EtatCivilTitulaire" },
          "lieuNaissance": { "$ref": "#/components/schemas/LieuNaissance" },
          "designation": { "$ref": "#/components/schemas/Designation" },
          "siret": { "type": "string" },
          "siren": { "type": "string" }
        }
      },
      "DemandeRestitVerifIban": {
        "type": "object",
        "properties": {
          "dateDemande": { "type": "string" },
          "motif": { "type": "string" },
          "siretDemandeur": { "type": "string" },
          "sirenDemandeur": { "type": "string" },
          "justification": { "type": "string" },
          "criteresRecherche": {
            "$ref": "#/components/schemas/CriteresRechercheVerifTitulaireIban"
          }
        }
      }
    },
    "responses": {
      "defaultErrorApim": {
        "description": "Erreurs retournées par la brique d'API Management DGFiP (voir guide pratique partenaire présent dans l'onglet documentation de l'API)",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "erreur": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "example": 84000
                    },
                    "message": {
                      "type": "string",
                      "example": "Anomalies bloquantes"
                    },
                    "horodatage": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2021-06-25T19:39:56+02:00"
                    }
                  }
                }
              }
            },
            "examples": {
              "ErreurJetonInvalide": {
                "description": "Utilisation d'un jeton d'authentification invalide ou expiré. (voir guide pratique partenaire présent dans l'onglet documentation de l'API)",
                "value": {
                  "erreur": {
                    "code": 900901,
                    "message": "Invalid Credentials",
                    "horodatage": "2021-06-16T18:50:58+02:00"
                  }
                }
              },
              "ErreurJetonAbsent": {
                "description": "Le jeton d'authentification n'est pas présent dans l'en-tête Authorization de la requête. (voir guide pratique partenaire présent dans l'onglet documentation de l'API)",
                "value": {
                  "erreur": {
                    "code": 900902,
                    "message": "Missing Credentials",
                    "horodatage": "2021-06-16T18:52:12+02:00"
                  }
                }
              },
              "ErreurScope": {
                "description": "Utilisation d'un jeton d'authentification ne présentant pas les scopes nécessaires à l'appel de la ressource ciblée. (voir guide pratique partenaire présent dans l'onglet documentation de l'API)",
                "value": {
                  "erreur": {
                    "code": 900910,
                    "message": "The access token does not allow you to access the requested resource",
                    "horodatage": "2020-11-06T10:50:03+01:00"
                  }
                }
              },
              "ErreurIdCorrelationAbsent": {
                "description": "L'identifiant de corrélation est absent de la requête dans l'en-tête X-Correlation-ID. (voir guide pratique partenaire présent dans l'onglet documentation de l'API)",
                "value": {
                  "erreur": {
                    "code": 910000,
                    "message": "Le paramètre X-Correlation-ID n'est pas présent dans le header HTTP",
                    "horodatage": "2021-06-167T18:57:37+0200"
                  }
                }
              },
              "ErreurQuotaAtteint": {
                "description": "Le quota d'appel souscrit a été dépassé. (voir guide pratique partenaire présent dans l'onglet documentation de l'API)",
                "value": {
                  "erreur": {
                    "code": 900804,
                    "message": "Message throttled out",
                    "horodatage": "2021-05-06T20:55:58+02:00"
                  }
                }
              }
            }
          }
        }
      }
    },
    "parameters": {
      "paramAuthorization": {
        "name": "Authorization",
        "in": "header",
        "description": "Jeton d'authentification. Header Authorization standard, utilisant un schéma Bearer. Exemple: \"bearer {token}\"",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": { "type": "string" }
      },
      "XCorrelationID": {
        "name": "X-Correlation-ID",
        "in": "header",
        "description": "Identifiant de corrélation de la requête (format UUID)",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
          "type": "string",
          "format": "uuid"
        },
        "example": "62d8e8ff-ce4f-4e50-b318-1edd2dab0f9f"
      }
    },
    "securitySchemes": {
      "Authorization": {
        "type": "oauth2",
        "description": "OAuth 2.0 avec un grant type Client Credentials. Header Authorization standard, utilisant un schéma Bearer. Exemple: \\\"Bearer {token}\\\"",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://IP-GATEWAY/token",
            "scopes": {}
          }
        }
      },
      "default": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://10.156.14.219:468/authorize",
            "scopes": {}
          }
        }
      }
    }
  }
}
